#######################################################>
###> Configure firewall for MySQL
#######################################################>
- name: Configure MySQL Firewall Settings
  hosts: mysql
  remote_user: ubuntu
  gather_facts: false
#  vars_prompt:
#    - name: password
#      prompt: Please provide creation password for "{{ my_user }}".
  vars_files:
    - vars/server_setup_vars.yml
    - vars/deployment_vars.yml

  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      connection: local
 
    - name: UFW - Allow ssh connections
      become: true
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp
        direction: in

    - name: UFW - Allow http/https connections
      become: true
      community.general.ufw:
        rule: allow
        port: '3306'
        proto: tcp
        direction: in

    - name: Brute-force attempt protection for SSH
      become: true
      community.general.ufw:
        rule: limit
        port: 22
        proto: tcp

    - name: UFW - Deny other incoming traffic and enable UFW
      become: true
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Remove excess packages no longer needed
      become: true
      ansible.builtin.apt:
        autoremove: yes

    - name: Reboot all hosts
      become: true
      ansible.builtin.reboot:
