##############################>
home:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
  vars:
    ansible_user: myuser
ec2hosts:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/product_certs/rsa_cert.pem
  hosts:

