###> This is the second file. 
###> Does not recreate nginx, only modifies it.

---
services:
  web:
    image: 00-----657660.dkr.ecr.us-west-2.amazonaws.com/apache2_php8.2
    container_name: smm_apache2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/html/:/var/www/html/

