
##############################################################################################
###> New Dockerfile  -> Richard Eric Walts as eric ---> 2023-06-24_15:16:37 init <<<
##############################################################################################
###> Apache2 container Ubuntu
#_#>

FROM 00-----657660.dkr.ecr.us-west-2.amazonaws.com/apache2_php8.2

WORKDIR .

###> copy configuration

COPY /var/docker/web/apache/index.php /var/www/html/index.php
###>  expose ports

EXPOSE 80, 443
 
