      - name: AWS - Create Secrets Manager Secret
        community.aws.secretsmanager_secret:
          name: "{{ item.secret_name }}"
          state: present
          secret_type: 'string'
          secret: "{{ item.secret_value }}"
