#######################################################>
###> This Ubuntu playbook performs initial settings: 
###> Updating packages to latest.
###> Set the prefered timzone 
###> Configure network time protocol
###> Change the SSH listening port
###> Insure root cannot direclty login over SSH
#######################################################>
- name: Initial server setup tasks
  hosts: ec2hosts
  remote_user: ubuntu
  gather_facts: false
#  vars_prompt:
#    - name: password
#      prompt: Please provide creation password for "{{ my_user }}".
  vars_files:
    - vars/server_setup_vars.yml
    - vars/asg_vars.yml

  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      connection: local
 
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    - name: Update installed packages
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Define prefered timezone
      become: true
      community.general.timezone:
        name: "{{ my_timezone }}"

    - name: Install zip
      become: true
      ansible.builtin.apt:
        name: zip
        state: present

    - name: Install pip
      become: true
      ansible.builtin.apt:
        name: pip
        state: present

    - name: Install curl
      become: true
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Install NFS server
      become: true
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present

    - name: Install NFS client
      become: true
      ansible.builtin.apt:
        name: nfs-common
        state: present

    - name: Make sure NTP service exists
      become: true
      ansible.builtin.apt:
        name: systemd-timesyncd
        state: present

    - name: Make sure NTP service is running
      become: true
      ansible.builtin.systemd:
        state: started
        name: systemd-timesyncd

    - name: Install boto 
      become: true
      ansible.builtin.shell: |
        pip install botocore
        pip install boto3

    - name: Install awscli
      become: true
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
   
    - name: Create the ssh group
      become: true
      ansible.builtin.group:
        name: "{{ ssh_group }}"
        state: present

    - name: Create the docker group
      become: true
      ansible.builtin.group:
        name: docker
        state: present

    - name: Make sure we have a 'sudo' group
      become: true
      ansible.builtin.group:
        name: sudo
        state: present

    - name: Create a user with sudo privileges
      become: true
      ansible.builtin.user:
        name: "{{ my_user }}"
        state: present
        groups: 
          - sudo
          - adm
          - docker
          - "{{ ssh_group }}"
        append: true
        create_home: true
        shell: /bin/bash
        password: "{{ lookup('ansible.builtin.env', 'MY_PASS') }}"
        update_password: on_create

    - name: Add ubuntu user to the allowed group
      become: true
      ansible.builtin.shell:
        usermod -a -G "{{ ssh_group }}" ubuntu

    - name: Set authorized key for remote user
      become: true
      ansible.posix.authorized_key:
        user: "{{ my_user }}"
        state: present
        key: "{{ copy_local_key }}"


    - name: Grant SUDO access
      become: true
      ansible.builtin.shell: |
        echo '{{ my_user }} ALL=(ALL) NOPASSWD:ALL'  >> '/tmp/01-{{ my_user }}-full'
        cp -f '/tmp/01-{{ my_user }}-full'  '/etc/sudoers.d/01-{{ my_user }}-full'

    - name: Disable remote login for root
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PermitRootLogin yes'
        line: 'PermitRootLogin no'

    - name: Configure SSH AllowGroups
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        line: 'AllowGroups "{{ ssh_group }}"'
        insertafter: '#VersionAddendum none'

    - name: UFW - Allow ssh connections
      become: true
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp
        direction: in

    - name: UFW - Allow http/https connections
      become: true
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
        direction: in

    - name: UFW - Allow http/https connections
      become: true
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp
        direction: in

    - name: UFW - Allow control plane connections
      become: true
      community.general.ufw:
        rule: allow
        port: '6443'
        proto: tcp
        direction: in

    - name: UFW - Allow k8s connections 
      become: true
      community.general.ufw:
        rule: allow
        port: 2379:2380
        proto: tcp
        direction: in

    - name: UFW - Allow k8s connections
      become: true
      community.general.ufw:
        rule: allow
        port: 10250:10259
        proto: tcp
        direction: in

    - name: Brute-force attempt protection for SSH
      become: true
      community.general.ufw:
        rule: limit
        port: 22
        proto: tcp

    - name: UFW - Deny other incoming traffic and enable UFW
      become: true
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Remove excess packages no longer needed
      become: true
      ansible.builtin.apt:
        autoremove: yes

    - name: Reboot all hosts
      become: true
      ansible.builtin.reboot:
