###> This is the second file. 
###> Does not recreate nginx, only modifies it.

---
services:
  web:
    build: .
    container_name: apache2_php82
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/html/:/var/www/html/

