- name: Add a volume to instance
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/asg_vars.yml
    - vars/aws_template_vars.yml
    - vars/server_setup_vars.yml
  tasks:
    - name: Pull new InstanceID
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          instance-state-name: [ "running" ]
          "tag:environment": "{{ new_env }}"
      register: instance_info

    - name: Show instance information
      ansible.builtin.debug:
        var:  instance_info['instances'][0].instance_id 


